/*
 * interface.c 
 *
 * Interface functions generated by Glade
 * 
 * Authored by Atul Raut <rauji.raut@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.
 *
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <ui/callbacks.h>
#include <ui/interface.h>
#include <ui/support.h>

#define GLADE_HOOKUP_OBJECT (component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
  gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF (component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

gboolean 
ui_interface_delete_event (GtkWidget *widget, GdkEvent *event, gpointer data)
{
  ll_cleanup_all_memory ();

  gtk_main_quit ();

  /* Change TRUE to FALSE and the main window will be destroyed with a "delete_event" */
  return TRUE;
}
